os: linux
dist: trusty
cache: false
sudo: required
language: bash
services: docker
env:
  matrix:
    - ARCH=x86_64 DISTRIB=debian
    - ARCH=x86_64 DISTRIB=alpine
    - ARCH=armhf DISTRIB=debian
    - ARCH=armhf DISTRIB=alpine
  global:
  - secure: hfTRtVguqzN5V3o26BZT35Ij7LBFG/9Dr7nunkHVd5OOjZlkacK557thYgVf6CO+bZ2kf5Hdg1lSGt+TodaDihDGpijr3rL09YBfiJlztFgifLGqkz0f6lNGlVYhTkQKyztNS/rRqEJDaMe9mxYKfigcuR69n6IZY29fQwHo5v2BDcXvxxPfQGWSLgGMJsv9MJ5t2YgV/su8kclpmXloHOQ0r2q4N0noyGaSjjOvwM3rJmCytA+NElF0q2mQWyjCNKQ+eKCrMwbg34S8rKela0VDDIwQPn4S5DqgwgpfiSE0TnmgXw12Njp298u4QrS1Ty6SUvnBsPcB9WKvVIz6NB4ItbUlrfhZ3xROwiSq770Rh6rR5SyaGAvRO4+Njw+JQoF3xCEeNwTgzw77c0L9yXjrJOJVjLQDmLOFVCSJO4I8CMoJlAOakm2jbQHfvDu38l4SoWeGyLvc8S9trW/YI9OmSdmMNj6kMyWq6WMiDDweq4D5WawtoZ953KztxTX5u+ZPdhST2aKD2+UytCNMGOBgYujzDPbhNsiMoz8hlEkO2s0qP+xb/7H8nizg87i7cwOjxNnvWRdzxaUevOtYcAZEwgVBOrY19zr8KOYefvy/KBJrQGnW0ERltef+h2+kxlnlGXNkmNjVtgTPYOgcq/vLoAIPlXmCC8DpRNmRFOg=
  - secure: sHooevgKQPub/DSgTbpNNYnKJeOuPKkEszbx5Yudzm3w5Q54Q11N1SKnhTWnSNjWwbp24PKubrBCBwOZBpEzVAHPPxLuBN2uio8R3rwy7JwcpJWyZ7lWDvpNjdl+HyFICaZRWK6VgBe7JjkFBPbduGV9fk3p6PjJEVhXsA9NaOowzxe5ho51u3xLPzhMnNXkpkIGWr1hxc5HGYhILlEWOQTC1XEsd6lzmKcQqlpTqUt/mUdtw56rmsfSFVyxLXddFzujDHAx86Weggr516VmUfG1T+W4QxtgFXdosPjq7PsBJbPgdPYBq1ZIFO+1dScERq5VM3krP6Ys8lvM2ikytH0d2xTTSoWfIdtKZkti3oE/efI6lhyDZ9yA+VhzKXWcDIuLuRyN5xJrTAcRXaC5jpkSrIuBwiLRnvvbzpUxbYZ8i4S7ZSiN3lLdfB07La3MSjkQFdjSbyOmz8AdB+tY8x7qbMGzfmYzSS8nl+Tn9pNFEJRcrCkzbqPUW/bsLawyX4GRpWK4s6hPjKW4wgLbpI9szENvdVVd2VDMHMq0x5rJc4p4O4TKq879x6OzggMlz1NgsZ9FqNbtJD2Iv1WWiloH3F/m5fi8pACnoAO58ax+TJcBtRPd3n2t5NU4l8NpR/qxG4twgx3uK46H5w28CCI/QUFbmnnX/paIxVAVags=
  - secure: LrDT8ivLjxNxeQcayV8pXBHDAzqWg2dgIoOLPE34yPnpGb9bTm5szbxQpy1J6GsxhuWtGu/9QBo5E5Xu4vyLsAP2eDchD3gbOaZnIl/qr4fjDGmlzs5FdPCNKrgLPuqfp6gY587bASQi3glZCQnFxnz+2WDr6THn0M7exDmMSUpGV1Acd5VVQqKktdeHTqESVSMhbEKs/3mH6US4dC0jLurapwd1L+kU8/IwRsanQIFkpV9CuPNHJWpjYMxohEMAK1RCWx4nY+U2rWvunva3yhj6a4eyk8YIbXk1JFL4dwp5aA8tAqQKGz795zpfQh6q5By6zK2OCXRDsY4QykVMkvXDUka7e3NmN64db31bFnir2YYaGySI4RRRCnP6VmlYn7QrV0MnUTLo2p/Kb8vLzIFEENEYkykJbcA8sxenbdoCJBjnHRkYtOF7p7No02kOm8D9bmE4xrWoTT8JIUzFD1O7O9YcInU9F0EI1/ACA7d3I5xgaIc+bx63Wq1jPPP8zKDTYpWnaIs908rJ2Uyeq6JTt3mnCMFcg5yr+QqofOywW4KZk2V2Ao2iY1gkuu0BXtMxmALh85RXxcXBeyzznRh2t2LXVbxi8v07yN+7u2QQt+sI/1hBfz5o9CogVmexHpf9MXewtL99i8bDRZSj7EloCXFZB9+Z+9ajTFWVOx8=
install: true
before_script:
- docker --version
- make --version
script:
  - make ARCH=${ARCH} DISTRIB=${DISTRIB} build 
after_success:
- docker login -u ${DOCKER_USER} -p ${DOCKER_PASS}
- make ARCH=${ARCH} DISTRIB=${DISTRIB} push
after_script:
- docker logout
- make clean
